//! MITS 88-DCDD physical two-board controller assembly.
//!
//! MITS split the controller across two S-100 cards. Board #1 owns address
//! selection and all computer input paths; Board #2 owns disk enable, function
//! control and write-side circuitry. They communicate only through the documented
//! controller harness, never through a direct card-to-card software reference.
//!
//! Phase 2 exposed the fixed 08h-0Ah register surface. Phase 3 places the real
//! disk-unit/buffer/FD-400 mechanics below the external controller cable while
//! preserving a no-drive default assembly and zero per-T-state card polling.

use std::cell::RefCell;
use std::rc::{Rc, Weak};

use rand::RngCore;

use super::fd400::{Fd400StepDirection, Fd400Time, Mits88DiskCableBus};
#[cfg(test)]
use super::fd400::{Fd400MechanicalSnapshot, MitsDiskUnit};
use crate::s100::{
    S100Card, S100CardClass, S100CardContact, S100CardDescriptor, S100ContactRole, S100Signal,
};
use crate::s100_backplane::{S100BusSample, S100CardDrive, S100ElectricalCard};

pub(crate) const DCDD_STATUS_CONTROL_PORT: u8 = 0x08;
pub(crate) const DCDD_SECTOR_CONTROL_PORT: u8 = 0x09;
pub(crate) const DCDD_DATA_PORT: u8 = 0x0a;

/// Active controller status is True=0 / False=1. With Disk Control disabled all
/// active functions are false while the two unused outputs D3/D4 are driven LOW.
const DISABLED_STATUS: u8 = 0xe7;

const PWR: S100CardContact = S100CardContact::new(S100Signal::Plus8V, S100ContactRole::Power);
const GND: S100CardContact = S100CardContact::new(S100Signal::Ground, S100ContactRole::Power);

/// Board #1 decodes the mirrored upper I/O-address byte. CLOC remains absent from
/// the card subscription deliberately: Phase-3 mechanics are epoch/deadline
/// derived and must not turn an idle controller into a 2 MHz polling workload.
const BOARD1_CONTACTS: &[S100CardContact] = &[
    PWR,
    GND,
    S100CardContact::new(S100Signal::Address(8), S100ContactRole::Input),
    S100CardContact::new(S100Signal::Address(9), S100ContactRole::Input),
    S100CardContact::new(S100Signal::Address(10), S100ContactRole::Input),
    S100CardContact::new(S100Signal::Address(11), S100ContactRole::Input),
    S100CardContact::new(S100Signal::Address(12), S100ContactRole::Input),
    S100CardContact::new(S100Signal::Address(13), S100ContactRole::Input),
    S100CardContact::new(S100Signal::Address(14), S100ContactRole::Input),
    S100CardContact::new(S100Signal::Address(15), S100ContactRole::Input),
    S100CardContact::new(S100Signal::Inp, S100ContactRole::Input),
    S100CardContact::new(S100Signal::Out, S100ContactRole::Input),
    S100CardContact::new(S100Signal::Write, S100ContactRole::Input),
    S100CardContact::new(S100Signal::DataBusIn, S100ContactRole::Input),
    S100CardContact::new(S100Signal::InterruptEnable, S100ContactRole::Input),
    S100CardContact::new(S100Signal::DataIn(0), S100ContactRole::TriStateOutput),
    S100CardContact::new(S100Signal::DataIn(1), S100ContactRole::TriStateOutput),
    S100CardContact::new(S100Signal::DataIn(2), S100ContactRole::TriStateOutput),
    S100CardContact::new(S100Signal::DataIn(3), S100ContactRole::TriStateOutput),
    S100CardContact::new(S100Signal::DataIn(4), S100ContactRole::TriStateOutput),
    S100CardContact::new(S100Signal::DataIn(5), S100ContactRole::TriStateOutput),
    S100CardContact::new(S100Signal::DataIn(6), S100ContactRole::TriStateOutput),
    S100CardContact::new(S100Signal::DataIn(7), S100ContactRole::TriStateOutput),
];

/// Board #2 samples Altair DO0..DO7 directly. DCL/CD/WDS are harness signals
/// generated by Board #1, not invented S-100 inputs on Board #2.
const BOARD2_CONTACTS: &[S100CardContact] = &[
    PWR,
    GND,
    S100CardContact::new(S100Signal::DataOut(0), S100ContactRole::Input),
    S100CardContact::new(S100Signal::DataOut(1), S100ContactRole::Input),
    S100CardContact::new(S100Signal::DataOut(2), S100ContactRole::Input),
    S100CardContact::new(S100Signal::DataOut(3), S100ContactRole::Input),
    S100CardContact::new(S100Signal::DataOut(4), S100ContactRole::Input),
    S100CardContact::new(S100Signal::DataOut(5), S100ContactRole::Input),
    S100CardContact::new(S100Signal::DataOut(6), S100ContactRole::Input),
    S100CardContact::new(S100Signal::DataOut(7), S100ContactRole::Input),
    S100CardContact::new(S100Signal::PowerOnClear, S100ContactRole::Input),
];

static MITS_88_DCDD_BOARD_1: S100CardDescriptor = S100CardDescriptor {
    key: "mits-88-dcdd-board-1",
    label: "MITS 88-DCDD Controller Board #1",
    class: S100CardClass::StorageController,
    historical: true,
    contacts: BOARD1_CONTACTS,
};

static MITS_88_DCDD_BOARD_2: S100CardDescriptor = S100CardDescriptor {
    key: "mits-88-dcdd-board-2",
    label: "MITS 88-DCDD Controller Board #2",
    class: S100CardClass::StorageController,
    historical: true,
    contacts: BOARD2_CONTACTS,
};

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
struct Board1HarnessDrive {
    dcl: bool,
    cd: bool,
    wds: bool,
}

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
struct Board2HarnessDrive {
    selected_drive: u8,
    disk_enable: bool,
}

#[derive(Debug, Default)]
struct Mits88DcddBoard2Circuit {
    selected_drive: u8,
    disk_control_enabled: bool,
}

/// Physical inter-board/controller-cable signal authority. `mechanics_time` is
/// one absolute virtual chassis time for the subsystem; advancing it is O(1) and
/// never loops over installed disk units. Individual FD-400 state is derived
/// lazily when a selected unit is observed or receives a command.
#[derive(Debug)]
struct Mits88DcddHarnessState {
    board1: Board1HarnessDrive,
    board2: Board2HarnessDrive,
    board2_sink: Weak<RefCell<Mits88DcddBoard2Circuit>>,
    external_disk_bus: Mits88DiskCableBus,
    mechanics_time: Fd400Time,
}

impl Default for Mits88DcddHarnessState {
    fn default() -> Self {
        Self {
            board1: Board1HarnessDrive::default(),
            board2: Board2HarnessDrive::default(),
            board2_sink: Weak::new(),
            external_disk_bus: Mits88DiskCableBus::default(),
            mechanics_time: Fd400Time::ZERO,
        }
    }
}

#[derive(Clone, Debug)]
pub(crate) struct Mits88DcddHarness {
    state: Rc<RefCell<Mits88DcddHarnessState>>,
}

impl Mits88DcddHarness {
    pub(crate) fn new() -> Self {
        Self {
            state: Rc::new(RefCell::new(Mits88DcddHarnessState::default())),
        }
    }

    pub(crate) fn board1_card(&self) -> Box<dyn S100ElectricalCard> {
        Box::new(Mits88DcddBoard1::new(self.clone()))
    }

    pub(crate) fn board2_card(&self) -> Box<dyn S100ElectricalCard> {
        let circuit = Rc::new(RefCell::new(Mits88DcddBoard2Circuit::default()));
        self.state.borrow_mut().board2_sink = Rc::downgrade(&circuit);
        Box::new(Mits88DcddBoard2 {
            harness: self.clone(),
            circuit,
        })
    }

    /// Advance the one controller/drive virtual-time epoch. The FD-400s are not
    /// ticked here; their rotation/deadlines are calculated only when observed.
    pub(crate) fn advance_mechanics_t_states(&self, t_states: u64) {
        if t_states == 0 {
            return;
        }
        let delta = Fd400Time::from_8080_t_states(t_states).units();
        let mut state = self.state.borrow_mut();
        state.mechanics_time = state.mechanics_time.saturating_add(delta);
    }

    /// Propagate a Board-1 harness transition immediately. Board #2 samples its
    /// own DO inputs from this same resolved S-100 sample, so behavior is neither
    /// slot-order dependent nor implemented as an idle polling loop.
    fn set_board1_drive(&self, drive: Board1HarnessDrive, sample: &S100BusSample) {
        let (previous, sink) = {
            let mut state = self.state.borrow_mut();
            let previous = state.board1;
            if previous == drive {
                return;
            }
            state.board1 = drive;
            (previous, state.board2_sink.clone())
        };

        if let Some(sink) = sink.upgrade() {
            sink.borrow_mut()
                .observe_harness_edge(previous, drive, sample, self);
        }
    }

    fn set_disk_selection(&self, address: u8, enabled: bool) {
        let mut state = self.state.borrow_mut();
        state.board2.selected_drive = address;
        state.board2.disk_enable = enabled;
    }

    fn disk_enabled(&self) -> bool {
        self.state.borrow().board2.disk_enable
    }

    fn drive_available(&self, address: u8) -> bool {
        self.state
            .borrow()
            .external_disk_bus
            .drive_available(address)
    }

    fn apply_drive_control(&self, address: u8, value: u8) {
        let mut state = self.state.borrow_mut();
        let now = state.mechanics_time;
        let Some(unit) = state.external_disk_bus.unit_mut(address) else {
            return;
        };
        let drive = unit.drive_mut();

        // Conflicting commands are left electrically asserted but do not invent
        // an ordering that the source material does not define.
        match (value & 0x01 != 0, value & 0x02 != 0) {
            (true, false) => {
                let _ = drive.step(Fd400StepDirection::In, now);
            }
            (false, true) => {
                let _ = drive.step(Fd400StepDirection::Out, now);
            }
            _ => {}
        }
        match (value & 0x04 != 0, value & 0x08 != 0) {
            (true, false) => drive.set_head_loaded(true, now),
            (false, true) => drive.set_head_loaded(false, now),
            _ => {}
        }
        // IE/ID/HCS/WRITE ENABLE belong to later controller phases. WDS write
        // data likewise remains inactive until the authentic write path exists.
    }

    #[cfg(test)]
    fn install_test_unit(&self, unit: MitsDiskUnit) {
        self.state.borrow_mut().external_disk_bus.install(unit);
    }

    #[cfg(test)]
    fn test_unit_snapshot(&self, address: u8) -> Option<Fd400MechanicalSnapshot> {
        let mut state = self.state.borrow_mut();
        let now = state.mechanics_time;
        Some(state.external_disk_bus.unit_mut(address)?.drive_mut().snapshot(now))
    }

    #[cfg(test)]
    fn same_physical_harness(&self, other: &Self) -> bool {
        Rc::ptr_eq(&self.state, &other.state)
    }
}

impl Mits88DcddBoard2Circuit {
    fn clear_disk_control(&mut self, harness: &Mits88DcddHarness) {
        self.disk_control_enabled = false;
        harness.set_disk_selection(self.selected_drive, false);
    }

    fn apply_dcl_rising(&mut self, value: u8, harness: &Mits88DcddHarness) {
        if value & 0x80 != 0 {
            self.clear_disk_control(harness);
            return;
        }

        self.selected_drive = value & 0x0f;
        self.disk_control_enabled = harness.drive_available(self.selected_drive);
        harness.set_disk_selection(self.selected_drive, self.disk_control_enabled);
    }

    fn observe_harness_edge(
        &mut self,
        previous: Board1HarnessDrive,
        current: Board1HarnessDrive,
        sample: &S100BusSample,
        harness: &Mits88DcddHarness,
    ) {
        if current.dcl && !previous.dcl {
            if let Some(value) = sample.data_out() {
                self.apply_dcl_rising(value, harness);
            }
        }

        if current.cd && !previous.cd && self.disk_control_enabled {
            if let Some(value) = sample.data_out() {
                harness.apply_drive_control(self.selected_drive, value);
            }
        }

        // The WDS edge is real, but write-data electronics/media mutation are
        // deliberately absent until the authentic write phase.
        let _wds_rising = current.wds && !previous.wds;
    }
}

struct Mits88DcddBoard1 {
    harness: Mits88DcddHarness,
    read_drive: Option<u8>,
    /// MITS does not define the power-up value of the read-data latches. Model
    /// that TTL state as indeterminate rather than claiming 00h/FFh/open bus.
    undefined_read_latch: u8,
}

impl Mits88DcddBoard1 {
    fn new(harness: Mits88DcddHarness) -> Self {
        Self {
            harness,
            read_drive: None,
            undefined_read_latch: rand::rng().next_u32() as u8,
        }
    }

    fn high_address(sample: &S100BusSample) -> Option<u8> {
        let mut value = 0u8;
        for bit in 0..8 {
            if sample.signal_level(S100Signal::Address(bit + 8))? {
                value |= 1 << bit;
            }
        }
        Some(value)
    }

    fn decoded_port(sample: &S100BusSample) -> Option<u8> {
        match Self::high_address(sample)? {
            DCDD_STATUS_CONTROL_PORT => Some(DCDD_STATUS_CONTROL_PORT),
            DCDD_SECTOR_CONTROL_PORT => Some(DCDD_SECTOR_CONTROL_PORT),
            DCDD_DATA_PORT => Some(DCDD_DATA_PORT),
            _ => None,
        }
    }

    fn status_byte(&self, sample: &S100BusSample) -> u8 {
        if !self.harness.disk_enabled() {
            return DISABLED_STATUS;
        }

        // Phase 3 still does not expose the complete enabled status byte because
        // Move Head's exact pulse waveform is not yet encoded. D5 already has a
        // proven source: S-100 pINTE. Normal production has no attached unit yet.
        let mut status = DISABLED_STATUS;
        if sample.signal_level(S100Signal::InterruptEnable) == Some(true) {
            status &= !(1 << 5);
        }
        status
    }

    fn update_read_drive(&mut self, sample: &S100BusSample) {
        let read_active = sample.signal_level(S100Signal::Inp) == Some(true)
            && sample.signal_level(S100Signal::DataBusIn) == Some(true);
        if !read_active {
            self.read_drive = None;
            return;
        }

        self.read_drive = match Self::decoded_port(sample) {
            Some(DCDD_STATUS_CONTROL_PORT) => Some(self.status_byte(sample)),
            // Sector output drivers are gated by Head Status. Production has no
            // attached unit in Phase 3, so the Phase-2 high-Z behavior remains.
            Some(DCDD_SECTOR_CONTROL_PORT) => None,
            // Read-data line drivers are selected even though the latch power-up
            // contents are undefined. Do not turn that into fictitious open bus.
            Some(DCDD_DATA_PORT) => Some(self.undefined_read_latch),
            _ => None,
        };
    }

    fn update_harness_strobes(&self, sample: &S100BusSample) {
        let write_active = sample.signal_level(S100Signal::Out) == Some(true)
            && sample.signal_level(S100Signal::Write) == Some(false);
        let selected = write_active.then(|| Self::decoded_port(sample)).flatten();
        self.harness.set_board1_drive(
            Board1HarnessDrive {
                dcl: selected == Some(DCDD_STATUS_CONTROL_PORT),
                cd: selected == Some(DCDD_SECTOR_CONTROL_PORT),
                wds: selected == Some(DCDD_DATA_PORT),
            },
            sample,
        );
    }
}

impl S100Card for Mits88DcddBoard1 {
    fn s100_descriptor(&self) -> &'static S100CardDescriptor {
        &MITS_88_DCDD_BOARD_1
    }
}

impl S100ElectricalCard for Mits88DcddBoard1 {
    fn observe_s100(&mut self, sample: &S100BusSample) {
        self.update_harness_strobes(sample);
        self.update_read_drive(sample);
    }

    fn drive_s100(&self) -> S100CardDrive {
        let mut drive = S100CardDrive::new();
        if let Some(value) = self.read_drive {
            drive.drive_data_in(value);
        }
        drive
    }

    fn external_drive_dirty(&self) -> bool {
        false
    }
}

struct Mits88DcddBoard2 {
    harness: Mits88DcddHarness,
    circuit: Rc<RefCell<Mits88DcddBoard2Circuit>>,
}

impl S100Card for Mits88DcddBoard2 {
    fn s100_descriptor(&self) -> &'static S100CardDescriptor {
        &MITS_88_DCDD_BOARD_2
    }
}

impl S100ElectricalCard for Mits88DcddBoard2 {
    fn observe_s100(&mut self, sample: &S100BusSample) {
        if sample.signal_level(S100Signal::PowerOnClear) == Some(true) {
            self.circuit.borrow_mut().clear_disk_control(&self.harness);
        }
    }

    fn drive_s100(&self) -> S100CardDrive {
        S100CardDrive::new()
    }

    fn external_drive_dirty(&self) -> bool {
        false
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::s100_backplane::{S100Backplane, S100PinDrive};

    fn io_sample(
        port: u8,
        inp: bool,
        out: bool,
        dbin: bool,
        wr_n: bool,
        data: u8,
    ) -> S100BusSample {
        let backplane = S100Backplane::new(0);
        let mut source = S100CardDrive::new();
        source.drive_address(u16::from(port) << 8);
        source.drive_data_out(data);
        source.drive_signal(S100Signal::Inp, inp);
        source.drive_signal(S100Signal::Out, out);
        source.drive_signal(S100Signal::DataBusIn, dbin);
        source.drive_signal(S100Signal::Write, wr_n);
        source.drive_signal(S100Signal::InterruptEnable, false);
        backplane.resolve_drive_sets(&[source])
    }

    fn board2_fixture(
        harness: &Mits88DcddHarness,
    ) -> (Mits88DcddBoard2, Rc<RefCell<Mits88DcddBoard2Circuit>>) {
        let circuit = Rc::new(RefCell::new(Mits88DcddBoard2Circuit::default()));
        harness.state.borrow_mut().board2_sink = Rc::downgrade(&circuit);
        (
            Mits88DcddBoard2 {
                harness: harness.clone(),
                circuit: circuit.clone(),
            },
            circuit,
        )
    }

    fn board1_harness_drive(harness: &Mits88DcddHarness) -> Board1HarnessDrive {
        harness.state.borrow().board1
    }

    fn install_ready_test_unit(harness: &Mits88DcddHarness, address: u8) {
        let mut unit = MitsDiskUnit::new(address).unwrap();
        unit.drive_mut().set_power(true, Fd400Time::ZERO);
        unit.drive_mut().set_door_open(false);
        unit.drive_mut().set_motor_on(true, Fd400Time::ZERO);
        harness.install_test_unit(unit);
    }

    #[test]
    fn both_controller_boards_share_one_harness_not_each_other() {
        let harness = Mits88DcddHarness::new();
        let board1 = Mits88DcddBoard1::new(harness.clone());
        let (board2, _) = board2_fixture(&harness);
        assert!(board1.harness.same_physical_harness(&board2.harness));
    }

    #[test]
    fn descriptors_split_real_s100_ownership_between_the_two_boards() {
        let harness = Mits88DcddHarness::new();
        let board1 = Mits88DcddBoard1::new(harness.clone());
        let (board2, _) = board2_fixture(&harness);
        let descriptor1 = board1.s100_descriptor();
        let descriptor2 = board2.s100_descriptor();

        assert_ne!(descriptor1.key, descriptor2.key);
        assert_eq!(descriptor1.class, S100CardClass::StorageController);
        assert_eq!(descriptor2.class, S100CardClass::StorageController);
        assert!(descriptor1.historical && descriptor2.historical);
        assert!(
            descriptor1
                .contacts
                .iter()
                .any(|c| c.signal == S100Signal::Address(15))
        );
        assert!(
            !descriptor1
                .contacts
                .iter()
                .any(|c| c.signal == S100Signal::DataOut(0))
        );
        assert!(
            descriptor2
                .contacts
                .iter()
                .any(|c| c.signal == S100Signal::DataOut(0))
        );
        assert!(
            !descriptor2
                .contacts
                .iter()
                .any(|c| c.signal == S100Signal::DataIn(0))
        );
    }

    #[test]
    fn board1_decodes_the_documented_high_address_byte_not_a_generic_low_byte() {
        let harness = Mits88DcddHarness::new();
        let mut board1 = Mits88DcddBoard1::new(harness);

        board1.observe_s100(&io_sample(0x08, true, false, true, true, 0));
        assert_eq!(board1.read_drive, Some(DISABLED_STATUS));

        let backplane = S100Backplane::new(0);
        let mut low_only = S100CardDrive::new();
        low_only.drive_address(0x0008);
        low_only.drive_signal(S100Signal::Inp, true);
        low_only.drive_signal(S100Signal::DataBusIn, true);
        low_only.drive_signal(S100Signal::Write, true);
        low_only.drive_signal(S100Signal::Out, false);
        low_only.drive_signal(S100Signal::InterruptEnable, false);
        board1.observe_s100(&backplane.resolve_drive_sets(&[low_only]));
        assert_eq!(board1.read_drive, None);
    }

    #[test]
    fn disabled_no_drive_status_is_exactly_e7_and_sector_port_is_high_z() {
        let harness = Mits88DcddHarness::new();
        let mut board1 = Mits88DcddBoard1::new(harness);

        board1.observe_s100(&io_sample(0x08, true, false, true, true, 0));
        assert_eq!(board1.read_drive, Some(0xe7));
        assert_eq!(
            board1
                .drive_s100()
                .pin(S100Signal::DataIn(0).pin().unwrap()),
            Some(S100PinDrive::Driven(true))
        );

        board1.observe_s100(&io_sample(0x09, true, false, true, true, 0));
        assert_eq!(board1.read_drive, None);
        let drive = board1.drive_s100();
        for bit in 0..8 {
            assert_eq!(
                drive.pin(S100Signal::DataIn(bit).pin().unwrap()),
                Some(S100PinDrive::HighZ)
            );
        }
    }

    #[test]
    fn board1_generates_only_the_documented_harness_strobe_for_each_out_port() {
        let harness = Mits88DcddHarness::new();
        let mut board1 = Mits88DcddBoard1::new(harness.clone());

        board1.observe_s100(&io_sample(0x08, false, true, false, false, 0x00));
        assert_eq!(
            board1_harness_drive(&harness),
            Board1HarnessDrive {
                dcl: true,
                cd: false,
                wds: false
            }
        );
        board1.observe_s100(&io_sample(0x09, false, true, false, false, 0x00));
        assert_eq!(
            board1_harness_drive(&harness),
            Board1HarnessDrive {
                dcl: false,
                cd: true,
                wds: false
            }
        );
        board1.observe_s100(&io_sample(0x0a, false, true, false, false, 0x00));
        assert_eq!(
            board1_harness_drive(&harness),
            Board1HarnessDrive {
                dcl: false,
                cd: false,
                wds: true
            }
        );
        board1.observe_s100(&io_sample(0x0b, false, true, false, false, 0x00));
        assert_eq!(
            board1_harness_drive(&harness),
            Board1HarnessDrive::default()
        );
    }

    #[test]
    fn harness_edge_reaches_board2_independent_of_card_observation_order() {
        let harness = Mits88DcddHarness::new();
        let mut board1 = Mits88DcddBoard1::new(harness.clone());
        let (_board2, circuit) = board2_fixture(&harness);

        board1.observe_s100(&io_sample(0x08, false, true, false, false, 0x03));

        assert_eq!(circuit.borrow().selected_drive, 3);
        assert!(!circuit.borrow().disk_control_enabled);
        assert!(!harness.disk_enabled());
    }

    #[test]
    fn board2_cannot_enable_a_missing_drive_and_d7_or_poc_clear_disk_control() {
        let harness = Mits88DcddHarness::new();
        let mut board1 = Mits88DcddBoard1::new(harness.clone());
        let (mut board2, circuit) = board2_fixture(&harness);

        board1.observe_s100(&io_sample(0x08, false, true, false, false, 0x03));
        assert_eq!(circuit.borrow().selected_drive, 3);
        assert!(!circuit.borrow().disk_control_enabled);
        assert!(!harness.disk_enabled());

        board1.observe_s100(&io_sample(0x08, false, true, false, true, 0x83));
        circuit.borrow_mut().disk_control_enabled = true;
        harness.set_disk_selection(3, true);
        board1.observe_s100(&io_sample(0x08, false, true, false, false, 0x83));
        assert!(!circuit.borrow().disk_control_enabled);
        assert!(!harness.disk_enabled());

        circuit.borrow_mut().disk_control_enabled = true;
        harness.set_disk_selection(3, true);
        let backplane = S100Backplane::new(0);
        let mut poc = S100CardDrive::new();
        poc.drive_signal(S100Signal::PowerOnClear, true);
        board2.observe_s100(&backplane.resolve_drive_sets(&[poc]));
        assert!(!circuit.borrow().disk_control_enabled);
        assert!(!harness.disk_enabled());
    }

    #[test]
    fn selected_drive_receives_head_and_step_commands_at_harness_virtual_time() {
        let harness = Mits88DcddHarness::new();
        let mut board1 = Mits88DcddBoard1::new(harness.clone());
        let (_board2, circuit) = board2_fixture(&harness);
        install_ready_test_unit(&harness, 3);

        board1.observe_s100(&io_sample(0x08, false, true, false, false, 0x03));
        assert!(circuit.borrow().disk_control_enabled);
        assert!(harness.disk_enabled());

        board1.observe_s100(&io_sample(0x09, false, true, false, false, 0x04));
        assert!(!harness.test_unit_snapshot(3).unwrap().head_status);
        harness.advance_mechanics_t_states(80_000); // 40 ms at 2 MHz.
        assert!(harness.test_unit_snapshot(3).unwrap().head_status);

        // Drop CD before asserting a new command so the next OUT creates a real
        // rising edge, exactly as consecutive 8080 I/O cycles do on the harness.
        board1.observe_s100(&io_sample(0x00, false, false, false, true, 0));
        board1.observe_s100(&io_sample(0x09, false, true, false, false, 0x01));
        harness.advance_mechanics_t_states(19_999);
        assert_eq!(harness.test_unit_snapshot(3).unwrap().track, 0);
        harness.advance_mechanics_t_states(1);
        let stepped = harness.test_unit_snapshot(3).unwrap();
        assert_eq!(stepped.track, 1);
        assert!(!stepped.head_status);
        harness.advance_mechanics_t_states(60_000); // now 40 ms after step command.
        assert!(harness.test_unit_snapshot(3).unwrap().head_status);
    }

    #[test]
    fn data_port_drives_an_indeterminate_latch_instead_of_claiming_open_bus() {
        let harness = Mits88DcddHarness::new();
        let mut board1 = Mits88DcddBoard1::new(harness);
        board1.undefined_read_latch = 0x5a;
        board1.observe_s100(&io_sample(0x0a, true, false, true, true, 0));
        assert_eq!(board1.read_drive, Some(0x5a));
        assert_eq!(
            board1
                .drive_s100()
                .pin(S100Signal::DataIn(1).pin().unwrap()),
            Some(S100PinDrive::Driven(true))
        );
    }

    #[test]
    fn controller_cards_still_have_no_asynchronous_s100_refresh_path() {
        let harness = Mits88DcddHarness::new();
        let board1 = Mits88DcddBoard1::new(harness.clone());
        let (board2, _) = board2_fixture(&harness);
        assert!(!board1.external_drive_dirty());
        assert!(!board2.external_drive_dirty());
    }
}