use std::collections::VecDeque;

use crate::config::{SioHardwareConfig, SioParity, SioRevision};

/// Logical state at the original 88-SIO board/interface boundary.
///
/// RSI and TSO are the board-side TTL serial levels. RIN and ROT themselves are
/// external pulses, so a stable snapshot cannot truthfully claim that a pulse is
/// still asserted after its edge; the two `*_device_ready` fields expose the
/// flip-flops set by those pulses. BIN/BOT are the resulting board busy outputs.
/// Idle asynchronous serial lines are MARK/HIGH.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(in crate::machine) struct SioHandshakeLines {
    pub rsi_high: bool,
    pub input_device_ready: bool,
    pub output_device_ready: bool,
    pub tso_high: bool,
    pub bin_high: bool,
    pub bot_high: bool,
}

impl Default for SioHandshakeLines {
    fn default() -> Self {
        Self {
            rsi_high: true,
            input_device_ready: false,
            output_device_ready: false,
            tso_high: true,
            bin_high: false,
            bot_high: false,
        }
    }
}

/// Digital COM2502/UART plus board-local handshake state used by one MITS
/// 88-SIO card.
///
/// The UART is double buffered in both directions. `tx_holding` is the
/// transmitter data-bits holding register (TBMT reflects this register), while
/// `tx_shift` is the active serial shift register. `rx_shift` is the receiver
/// shift register and `rx_data` is the receiver data-bits holding register
/// (RDA reflects the latter).
///
/// The Rev0 input/output device-ready flip-flops are deliberately separate from
/// COM2502 RDA/TBMT. An external device must pulse RIN/ROT explicitly; receiving
/// a serial character or freeing the UART transmitter does not fabricate those
/// handshake pulses.
pub(in crate::machine) struct SioPort {
    config: SioHardwareConfig,
    bit_phase_numerator: u64,

    rx_data: u8,
    rx_full: bool,
    rx_shift: Option<(u8, bool, bool)>,
    rx_bits_remaining: u8,
    /// External receive line forced continuously to SPACE/LOW. This is a line
    /// condition (for example the ASR-33 BREAK key), never an ASCII NUL byte.
    rx_break_active: bool,
    /// Distinguishes a synthetic receiver frame generated by a held BREAK from
    /// a normal endpoint character already travelling through the shift path.
    rx_shift_from_break: bool,
    overrun: bool,
    framing_error: bool,
    parity_error: bool,

    tx_holding: Option<u8>,
    tx_shift: Option<u8>,
    tx_bits_remaining: u8,
    wire_tx: VecDeque<u8>,

    /// Original Rev0 external device-ready latches (IC F-a/F-b in the MITS
    /// documentation). `false` is the reset/not-ready state. The connector-side
    /// RIN/ROT ready pulse sets the respective latch; DATA IN/DATA OUT reset it.
    input_device_ready: bool,
    output_device_ready: bool,
}

impl Default for SioPort {
    fn default() -> Self { Self::new(SioHardwareConfig::default()) }
}

impl SioPort {
    pub(in crate::machine) fn new(config: SioHardwareConfig) -> Self {
        Self {
            config,
            bit_phase_numerator: 0,
            rx_data: 0,
            rx_full: false,
            rx_shift: None,
            rx_bits_remaining: 0,
            rx_break_active: false,
            rx_shift_from_break: false,
            overrun: false,
            framing_error: false,
            parity_error: false,
            tx_holding: None,
            tx_shift: None,
            tx_bits_remaining: 0,
            wire_tx: VecDeque::new(),
            input_device_ready: false,
            output_device_ready: false,
        }
    }

    pub(in crate::machine) fn configure(&mut self, config: SioHardwareConfig) {
        if self.config == config { return; }
        *self = Self::new(config);
    }

    pub(in crate::machine) fn config(&self) -> SioHardwareConfig { self.config }

    pub(in crate::machine) fn clear(&mut self) {
        let config = self.config;
        *self = Self::new(config);
    }

    pub(in crate::machine) fn receive_line_idle(&self) -> bool { self.rx_shift.is_none() }
    pub(in crate::machine) fn receive_len(&self) -> usize {
        usize::from(self.rx_full) + usize::from(self.rx_shift.is_some())
    }
    pub(in crate::machine) fn rx_full(&self) -> bool { self.rx_full }
    pub(in crate::machine) fn tx_buffer_empty(&self) -> bool { self.tx_holding.is_none() }

    /// External connector RIN ready pulse. This sets only the original Rev0
    /// input-device-ready flip-flop; it is intentionally independent of RDA.
    pub(in crate::machine) fn pulse_input_device_ready(&mut self) {
        self.input_device_ready = true;
    }

    /// External connector ROT ready pulse. This sets only the original Rev0
    /// output-device-ready flip-flop; it is intentionally independent of TBMT.
    pub(in crate::machine) fn pulse_output_device_ready(&mut self) {
        self.output_device_ready = true;
    }

    pub(in crate::machine) fn input_device_ready(&self) -> bool { self.input_device_ready }
    pub(in crate::machine) fn output_device_ready(&self) -> bool { self.output_device_ready }

    fn parity_bit(&self, value: u8) -> bool {
        let bits = self.config.format.data_bits.bits();
        let mask = if bits == 8 { 0xff } else { ((1u16 << bits) - 1) as u8 };
        let odd_ones = (value & mask).count_ones() & 1 != 0;
        match self.config.format.parity {
            SioParity::None => true,
            // Even parity bit is HIGH exactly when the data contains an odd
            // number of ones; odd parity is the inverse.
            SioParity::Even => odd_ones,
            SioParity::Odd => !odd_ones,
        }
    }

    fn break_parity_error(&self) -> bool {
        // A held BREAK presents SPACE/LOW during the parity bit as well. Compare
        // that literal LOW with the configured parity bit for all-zero data.
        self.config.format.parity != SioParity::None && self.parity_bit(0)
    }

    fn start_break_frame_if_idle(&mut self) {
        if !self.rx_break_active || self.rx_shift.is_some() { return; }
        self.rx_shift = Some((0, true, self.break_parity_error()));
        self.rx_bits_remaining = self.config.format.frame_bits();
        self.rx_shift_from_break = true;
    }

    /// Drive or release a physical receive BREAK. BREAK is continuous SPACE on
    /// RSI, not a special character. A held BREAK therefore produces zero-data
    /// frames with a missing stop bit (framing error); if it remains held, the
    /// next frame begins immediately and can naturally produce UART overrun.
    pub(in crate::machine) fn set_receive_break(&mut self, active: bool) {
        if self.rx_break_active == active { return; }
        self.rx_break_active = active;
        if active {
            self.start_break_frame_if_idle();
        } else if self.rx_shift_from_break {
            // Releasing BREAK returns the wire to MARK immediately. An incomplete
            // synthetic BREAK frame has not reached RDA and must not become a
            // phantom NUL merely because the key was released.
            self.rx_shift = None;
            self.rx_bits_remaining = 0;
            self.rx_shift_from_break = false;
        }
    }

    fn frame_bit(
        &self,
        value: u8,
        bits_remaining: u8,
        framing_error: bool,
        parity_error: bool,
    ) -> bool {
        let frame_bits = self.config.format.frame_bits();
        if bits_remaining == 0 || bits_remaining > frame_bits { return true; }
        let index = frame_bits - bits_remaining;
        if index == 0 { return false; } // start bit

        let data_bits = self.config.format.data_bits.bits();
        if index <= data_bits {
            return value & (1u8 << (index - 1)) != 0; // asynchronous LSB first
        }

        let parity_present = self.config.format.parity != SioParity::None;
        let parity_index = 1 + data_bits;
        if parity_present && index == parity_index {
            return self.parity_bit(value) ^ parity_error;
        }

        // Stop field. A framing error represents the first expected stop bit
        // arriving as SPACE/LOW; any second configured stop bit remains MARK.
        let first_stop_index = parity_index + u8::from(parity_present);
        if framing_error && index == first_stop_index { false } else { true }
    }

    fn rsi_high(&self) -> bool {
        if self.rx_break_active { return false; }
        self.rx_shift.map_or(true, |(value, framing_error, parity_error)| {
            self.frame_bit(value, self.rx_bits_remaining, framing_error, parity_error)
        })
    }

    fn tso_high(&self) -> bool {
        self.tx_shift.map_or(true, |value| {
            self.frame_bit(value, self.tx_bits_remaining, false, false)
        })
    }

    pub(in crate::machine) fn handshake_lines(&self) -> SioHandshakeLines {
        SioHandshakeLines {
            rsi_high: self.rsi_high(),
            input_device_ready: self.input_device_ready,
            output_device_ready: self.output_device_ready,
            tso_high: self.tso_high(),
            // MITS describes DATA IN/OUT as resetting the corresponding ready
            // latch to clear the busy signal to the device. The latch assertion
            // therefore owns the logical BIN/BOT busy level.
            bin_high: self.input_device_ready,
            bot_high: self.output_device_ready,
        }
    }

    /// Begin one real serial receive frame. A full unread holding register does
    /// not stop the COM2502 receiver shift register; the resulting overwrite is
    /// handled only when this new frame completes.
    pub(in crate::machine) fn queue_received_character(&mut self, value: u8) {
        if !self.receive_line_idle() || self.rx_break_active { return; }
        self.rx_shift = Some((value, false, false));
        self.rx_bits_remaining = self.config.format.frame_bits();
        self.rx_shift_from_break = false;
    }

    /// Debugger injection bypasses serial line time but retains COM2502 holding
    /// register / overrun semantics. It does NOT synthesize an external RIN pulse.
    pub(in crate::machine) fn debugger_inject_received_character(&mut self, value: u8) {
        self.complete_received_character(value, false, false);
    }

    fn complete_received_character(&mut self, value: u8, framing_error: bool, parity_error: bool) {
        // COM2502 differs importantly from MC6850: at completion it first notes
        // whether RDA was already high (overrun), then transfers the NEW shift
        // register contents into the receiver holding register. The old unread
        // character is therefore overwritten.
        self.overrun = self.rx_full;
        let bits = self.config.format.data_bits.bits();
        let mask = if bits == 8 { 0xff } else { ((1u16 << bits) - 1) as u8 };
        self.rx_data = value & mask;
        self.rx_full = true;
        self.framing_error = framing_error;
        self.parity_error = self.config.format.parity != crate::config::SioParity::None && parity_error;
    }

    pub(in crate::machine) fn read_data(&mut self) -> u8 {
        let value = self.rx_data;
        // The board pulses RDAR when the CPU reads the data channel. COM2502
        // specifies RDAR as resetting RDA; error outputs are status-register
        // state and are refreshed by reception/master reset, not fabricated as
        // a side effect of this data read.
        self.rx_full = false;
        // Original Rev0 DATA IN also resets IC F-a. This is a separate action
        // from RDAR and is why RIN must be asserted again by the external device.
        if self.config.revision == SioRevision::Rev0 {
            self.input_device_ready = false;
        }
        value
    }

    pub(in crate::machine) fn peek_data(&self) -> u8 { self.rx_data }

    pub(in crate::machine) fn clear_receive_for_debugger(&mut self) {
        self.rx_full = false;
        self.rx_shift = None;
        self.rx_bits_remaining = 0;
        self.rx_shift_from_break = false;
        self.overrun = false;
        self.framing_error = false;
        self.parity_error = false;
        self.start_break_frame_if_idle();
    }

    pub(in crate::machine) fn write_data(&mut self, value: u8) {
        // Original Rev0 DATA OUT resets IC F-b before/with the UART TDS strobe,
        // clearing BOT/busy and requiring a later external ROT ready pulse.
        if self.config.revision == SioRevision::Rev0 {
            self.output_device_ready = false;
        }
        self.tx_holding = Some(value);
        // COM2502 loads an idle transmitter shift register immediately from the
        // holding register. TBMT therefore returns HIGH even though the serial
        // character is still physically transmitting.
        if self.tx_shift.is_none() { self.promote_tx_holding(); }
    }

    fn promote_tx_holding(&mut self) {
        if self.tx_shift.is_some() { return; }
        let Some(value) = self.tx_holding.take() else { return; };
        self.tx_shift = Some(value);
        self.tx_bits_remaining = self.config.format.frame_bits();
    }

    pub(in crate::machine) fn endpoint_tx_front(&self) -> Option<u8> { self.wire_tx.front().copied() }
    pub(in crate::machine) fn endpoint_tx_complete(&mut self) -> Option<u8> { self.wire_tx.pop_front() }
    pub(in crate::machine) fn endpoint_tx_pending_or_hardware_busy(&self) -> bool {
        !self.wire_tx.is_empty() || self.tx_holding.is_some() || self.tx_shift.is_some()
    }

    pub(in crate::machine) fn clear_transmit_for_debugger(&mut self) {
        self.tx_holding = None;
        self.tx_shift = None;
        self.tx_bits_remaining = 0;
        self.wire_tx.clear();
    }

    pub(in crate::machine) fn debugger_complete_one_tx(&mut self) -> Option<u8> {
        if let Some(byte) = self.wire_tx.pop_front() { return Some(byte); }
        if self.tx_shift.is_none() { self.promote_tx_holding(); }
        let byte = self.tx_shift.take()?;
        self.tx_bits_remaining = 0;
        self.promote_tx_holding();
        Some(byte)
    }

    pub(in crate::machine) fn status(&self) -> u8 {
        let errors = (u8::from(self.overrun) << 4)
            | (u8::from(self.framing_error) << 3)
            | (u8::from(self.parity_error) << 2);
        match self.config.revision {
            // Original status word keeps COM2502 RDA on D5 and TBMT on D1, both
            // active HIGH. D0/D7 are *separate* active-low external device-ready
            // flip-flops: HIGH means no RIN/ROT ready pulse is currently latched.
            SioRevision::Rev0 => {
                errors
                    | (u8::from(!self.output_device_ready) << 7)
                    | (u8::from(self.rx_full) << 5)
                    | (u8::from(self.tx_buffer_empty()) << 1)
                    | u8::from(!self.input_device_ready)
            }
            // Rev 1 modification: receive ready is D0 active LOW and transmit
            // buffer empty is D7 active LOW. Error positions remain D4:D2.
            SioRevision::Rev1 => {
                errors
                    | u8::from(!self.rx_full)
                    | (u8::from(!self.tx_buffer_empty()) << 7)
            }
        }
    }

    fn transmitter_bit_boundary(&mut self) {
        let Some(byte) = self.tx_shift else {
            self.promote_tx_holding();
            return;
        };
        if self.tx_bits_remaining > 1 {
            self.tx_bits_remaining -= 1;
            return;
        }
        if self.tx_bits_remaining == 1 {
            self.tx_bits_remaining = 0;
            self.tx_shift = None;
            self.wire_tx.push_back(byte);
            self.promote_tx_holding();
        }
    }

    fn receiver_bit_boundary(&mut self) {
        let Some((value, framing_error, parity_error)) = self.rx_shift else {
            self.start_break_frame_if_idle();
            return;
        };
        if self.rx_bits_remaining > 1 {
            self.rx_bits_remaining -= 1;
            return;
        }
        if self.rx_bits_remaining == 1 {
            let from_break = self.rx_shift_from_break;
            self.rx_bits_remaining = 0;
            self.rx_shift = None;
            self.rx_shift_from_break = false;
            self.complete_received_character(
                value,
                framing_error || self.rx_break_active,
                parity_error || (self.rx_break_active && self.break_parity_error()),
            );
            if from_break || self.rx_break_active {
                self.start_break_frame_if_idle();
            }
        }
    }

    /// Advance the independent 88-SIO baud clock by elapsed chassis T-states.
    /// `baud` is the serial bit rate; the physical COM2502 receives a 16x clock,
    /// but its internal divider yields exactly one serial bit boundary per
    /// `cpu_clock_hz / baud` elapsed chassis quanta.
    pub(in crate::machine) fn advance_t_states(&mut self, t_states: u64, cpu_clock_hz: u32) {
        if t_states == 0 || cpu_clock_hz == 0 { return; }
        let baud = self.config.baud.baud();
        if baud == 0 { return; }
        let total = self.bit_phase_numerator
            .saturating_add(t_states.saturating_mul(u64::from(baud)));
        let threshold = u64::from(cpu_clock_hz);
        let boundaries = total / threshold;
        self.bit_phase_numerator = total % threshold;
        for _ in 0..boundaries {
            self.transmitter_bit_boundary();
            self.receiver_bit_boundary();
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{SioBaudRate, SioStopBits, SioWordFormat};

    const TWO_MHZ: u32 = 2_000_000;

    fn config(revision: SioRevision) -> SioHardwareConfig {
        SioHardwareConfig { revision, ..SioHardwareConfig::default() }
    }

    #[test]
    fn rev0_and_rev1_ready_flags_have_historical_positions_and_polarity() {
        let mut rev0 = SioPort::new(config(SioRevision::Rev0));
        let mut rev1 = SioPort::new(config(SioRevision::Rev1));
        assert_eq!(rev0.status(), 0x83, "Rev0 starts with external device-ready latches reset while TBMT is D1 active high");
        assert_eq!(rev1.status(), 0x01, "Rev1 not-RDA is D0 high while empty; D7 low means TX ready");

        rev0.debugger_inject_received_character(b'R');
        rev1.debugger_inject_received_character(b'R');
        assert_eq!(rev0.status() & 0x20, 0x20, "Rev0 RDA is D5 active high");
        assert_eq!(rev0.status() & 0x81, 0x81, "COM2502 RDA must not fabricate external Rev0 RIN/ROT ready state");
        assert_eq!(rev1.status() & 0x01, 0x00, "Rev1 receive-ready is D0 active low");

        rev0.write_data(b'A');
        rev1.write_data(b'A');
        // Idle shift register consumes holding data immediately, so TBMT is
        // already ready again while the character itself remains in flight.
        assert_eq!(rev0.status() & 0x02, 0x02);
        assert_eq!(rev1.status() & 0x80, 0x00);
        rev0.write_data(b'B');
        rev1.write_data(b'B');
        assert_eq!(rev0.status() & 0x02, 0x00, "second byte occupies Rev0 holding register");
        assert_eq!(rev1.status() & 0x80, 0x80, "second byte makes Rev1 active-low TX ready false");
    }

    #[test]
    fn rev0_device_ready_flip_flops_follow_external_pulses_and_data_handshake() {
        let mut p = SioPort::new(config(SioRevision::Rev0));
        assert_eq!(p.status() & 0x81, 0x81);
        assert_eq!(p.handshake_lines(), SioHandshakeLines::default());

        p.pulse_input_device_ready();
        let lines = p.handshake_lines();
        assert!(lines.input_device_ready);
        assert!(lines.bin_high);
        assert_eq!(p.status() & 0x01, 0x00, "RIN sets the active-low D0 device-ready indication");
        assert_eq!(p.status() & 0x20, 0x00, "RIN is not COM2502 RDA");

        p.debugger_inject_received_character(b'I');
        assert_eq!(p.status() & 0x21, 0x20, "RDA may coexist with independently latched RIN ready");
        assert_eq!(p.read_data(), b'I');
        assert_eq!(p.status() & 0x21, 0x01, "DATA IN resets both RDAR and the separate input-ready latch");
        assert!(!p.handshake_lines().bin_high);

        p.pulse_output_device_ready();
        let lines = p.handshake_lines();
        assert!(lines.output_device_ready);
        assert!(lines.bot_high);
        assert_eq!(p.status() & 0x80, 0x00, "ROT sets the active-low D7 output-device-ready indication");
        p.write_data(b'O');
        assert_eq!(p.status() & 0x80, 0x80, "DATA OUT resets F-b independently of COM2502 TBMT");
        assert!(!p.handshake_lines().bot_high);
    }

    #[test]
    fn serial_rsi_and_tso_follow_real_async_frame_bits() {
        let mut c = config(SioRevision::Rev1);
        c.baud = SioBaudRate::try_new(9_600).unwrap();
        c.format = SioWordFormat { stop_bits: SioStopBits::One, ..SioWordFormat::default() };
        let mut p = SioPort::new(c);
        assert!(p.handshake_lines().rsi_high && p.handshake_lines().tso_high, "idle asynchronous lines are MARK/HIGH");

        // 0x01 8N1: start LOW, D0 HIGH, D1..D7 LOW, stop HIGH.
        p.queue_received_character(0x01);
        p.write_data(0x01);
        assert!(!p.handshake_lines().rsi_high);
        assert!(!p.handshake_lines().tso_high);
        p.advance_t_states(209, TWO_MHZ); // first 9600-baud bit boundary
        assert!(p.handshake_lines().rsi_high);
        assert!(p.handshake_lines().tso_high);
        p.advance_t_states(209, TWO_MHZ);
        assert!(!p.handshake_lines().rsi_high);
        assert!(!p.handshake_lines().tso_high);
        p.advance_t_states(1_666, TWO_MHZ);
        assert!(p.handshake_lines().rsi_high, "completed RX frame returns RSI to idle MARK");
        assert!(p.handshake_lines().tso_high, "completed TX frame returns TSO to idle MARK");
    }

    #[test]
    fn held_receive_break_is_continuous_space_and_produces_zero_with_framing_error() {
        let mut p = SioPort::new(config(SioRevision::Rev1));
        p.set_receive_break(true);
        assert!(!p.receive_line_idle());
        assert!(!p.handshake_lines().rsi_high, "BREAK forces RSI to SPACE/LOW immediately");

        p.advance_t_states(200_000, TWO_MHZ); // 110 baud, default 8N2 = 11 bits
        assert_eq!(p.peek_data(), 0x00);
        assert_eq!(p.status() & 0x09, 0x08, "RDA ready plus framing error after one BREAK frame");
        assert!(!p.receive_line_idle(), "held BREAK immediately begins another receiver frame");
        assert!(!p.handshake_lines().rsi_high);

        p.advance_t_states(200_000, TWO_MHZ);
        assert_eq!(p.status() & 0x18, 0x18, "continued BREAK can naturally overrun the unread COM2502 holding register");

        p.set_receive_break(false);
        assert!(p.receive_line_idle());
        assert!(p.handshake_lines().rsi_high, "releasing BREAK returns RSI to idle MARK");
        assert_eq!(p.read_data(), 0x00);
    }

    #[test]
    fn short_receive_break_release_does_not_fabricate_a_nul_character() {
        let mut p = SioPort::new(config(SioRevision::Rev1));
        p.set_receive_break(true);
        p.advance_t_states(50_000, TWO_MHZ);
        p.set_receive_break(false);
        assert!(p.receive_line_idle());
        assert!(p.handshake_lines().rsi_high);
        assert!(!p.rx_full());
        assert_eq!(p.status() & 0x09, 0x01);
    }

    #[test]
    fn com2502_overrun_overwrites_old_unread_character_with_new_character() {
        let mut p = SioPort::new(config(SioRevision::Rev1));
        p.debugger_inject_received_character(b'A');
        p.debugger_inject_received_character(b'B');
        assert_eq!(p.status() & 0x10, 0x10);
        assert_eq!(p.read_data(), b'B', "COM2502 transfers the new shift-register character into the holding register");
        assert_eq!(p.status() & 0x01, 0x01, "data read resets RDA");
        assert_eq!(p.status() & 0x10, 0x10, "RDAR does not fabricate an error clear");
        p.debugger_inject_received_character(b'C');
        assert_eq!(p.status() & 0x10, 0x00, "next reception with RDA previously low refreshes overrun false");
    }

    #[test]
    fn double_buffered_transmitter_returns_tbmt_before_character_finishes() {
        let mut c = config(SioRevision::Rev1);
        c.baud = SioBaudRate::try_new(9_600).unwrap();
        c.format = SioWordFormat { stop_bits: SioStopBits::One, ..SioWordFormat::default() };
        let mut p = SioPort::new(c);
        p.write_data(b'A');
        assert_eq!(p.status() & 0x80, 0, "holding register is already empty after idle promotion");
        assert_eq!(p.endpoint_tx_front(), None);
        p.write_data(b'B');
        assert_eq!(p.status() & 0x80, 0x80, "holding register now contains the next byte");

        p.advance_t_states(2_083, TWO_MHZ);
        assert_eq!(p.endpoint_tx_front(), None);
        p.advance_t_states(1, TWO_MHZ);
        assert_eq!(p.endpoint_tx_front(), Some(b'A'));
        assert_eq!(p.status() & 0x80, 0, "B promoted at the exact A frame boundary");
    }

    #[test]
    fn unread_rda_does_not_stop_receiver_shift_and_real_overrun_occurs_after_next_frame() {
        let mut p = SioPort::new(config(SioRevision::Rev1));
        p.queue_received_character(b'A');
        p.advance_t_states(200_000, TWO_MHZ); // 110 baud, 8N2 => 100 ms
        assert!(!p.receive_line_idle() || p.rx_full());
        if !p.receive_line_idle() { p.advance_t_states(1, TWO_MHZ); }
        assert!(p.rx_full());
        assert!(p.receive_line_idle());
        p.queue_received_character(b'B');
        p.advance_t_states(200_001, TWO_MHZ);
        assert_eq!(p.status() & 0x10, 0x10);
        assert_eq!(p.peek_data(), b'B');
    }
}
