#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Cpu8080Inputs {
    /// Value presented to the 8080 data bus while DBIN is active.
    pub data_in: u8,
    /// READY sampled by the processor. Low inserts TW states.
    pub ready: bool,
    /// Maskable interrupt request input.
    pub interrupt: bool,
    /// DMA/bus-hold request input.
    pub hold: bool,
    /// Asynchronous RESET input.
    pub reset: bool,
}

impl Default for Cpu8080Inputs {
    fn default() -> Self {
        Self {
            data_in: 0,
            ready: true,
            interrupt: false,
            hold: false,
            reset: false,
        }
    }
}

/// Externally visible Intel 8080 package-pin state.
///
/// `phi1`/`phi2` are inputs generated by the physical MITS CPU board. They live
/// here because this structure represents what is electrically present at the
/// package boundary, not only processor outputs. `address` and `data_out` use
/// `Option` so HOLD/HLDA tri-state behavior is explicit.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Cpu8080Pins {
    /// Intel 8080 pin 22, first non-overlapping clock phase.
    pub phi1: bool,
    /// Intel 8080 pin 15, second non-overlapping clock phase.
    pub phi2: bool,
    pub address: Option<u16>,
    pub data_out: Option<u8>,
    pub sync: bool,
    pub dbin: bool,
    /// Physical /WR output. `false` means write asserted.
    pub wr_n: bool,
    pub inte: bool,
    pub wait: bool,
    pub hlda: bool,
}

impl Default for Cpu8080Pins {
    fn default() -> Self {
        Self {
            phi1: false,
            phi2: false,
            address: None,
            data_out: None,
            sync: false,
            dbin: false,
            wr_n: true,
            inte: false,
            wait: false,
            hlda: false,
        }
    }
}
