use std::time::Duration;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CpuModel {
    Intel8080,
}

impl CpuModel {
    pub const ALL: [Self; 1] = [Self::Intel8080];

    pub const fn label(self) -> &'static str {
        match self {
            Self::Intel8080 => "Intel 8080",
        }
    }

    /// Clock generated by the original Altair CPU board's 2.000 MHz crystal.
    pub const fn clock_hz(self) -> u32 {
        match self {
            Self::Intel8080 => 2_000_000,
        }
    }
}

impl Default for CpuModel {
    fn default() -> Self {
        Self::Intel8080
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RamSize {
    Bytes256,
    K1,
    K4,
    K8,
    K16,
    K32,
    K48,
    K64,
}

impl RamSize {
    pub const ALL: [Self; 8] = [
        Self::Bytes256,
        Self::K1,
        Self::K4,
        Self::K8,
        Self::K16,
        Self::K32,
        Self::K48,
        Self::K64,
    ];

    pub const fn bytes(self) -> usize {
        match self {
            Self::Bytes256 => 256,
            Self::K1 => 1024,
            Self::K4 => 4 * 1024,
            Self::K8 => 8 * 1024,
            Self::K16 => 16 * 1024,
            Self::K32 => 32 * 1024,
            Self::K48 => 48 * 1024,
            Self::K64 => 64 * 1024,
        }
    }

    pub const fn label(self) -> &'static str {
        match self {
            Self::Bytes256 => "256 bytes",
            Self::K1 => "1 KiB",
            Self::K4 => "4 KiB",
            Self::K8 => "8 KiB",
            Self::K16 => "16 KiB",
            Self::K32 => "32 KiB",
            Self::K48 => "48 KiB",
            Self::K64 => "64 KiB",
        }
    }
}

impl Default for RamSize {
    fn default() -> Self {
        Self::K8
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RamInit {
    Random,
    Zeroed,
}

impl RamInit {
    pub const ALL: [Self; 2] = [Self::Random, Self::Zeroed];

    pub const fn label(self) -> &'static str {
        match self {
            Self::Random => "Random power-on contents",
            Self::Zeroed => "Zero-filled",
        }
    }
}

impl Default for RamInit {
    fn default() -> Self {
        Self::Random
    }
}

/// MITS serial interface installed in the emulated Altair.
///
/// The standard MITS console port assignments are used. Only the selected
/// board decodes its ports; this is hardware configuration, not a compatibility
/// alias that exposes both interfaces at once.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SerialBoard {
    Sio88,
    TwoSio88,
}

impl SerialBoard {
    pub const ALL: [Self; 2] = [Self::Sio88, Self::TwoSio88];

    pub const fn label(self) -> &'static str {
        match self {
            Self::Sio88 => "MITS 88-SIO",
            Self::TwoSio88 => "MITS 88-2SIO",
        }
    }

    /// Status/control address of the board's first serial port.
    pub const fn status_port(self) -> u8 {
        match self {
            Self::Sio88 => 0x00,
            Self::TwoSio88 => 0x10,
        }
    }

    /// Data address of the board's first serial port.
    pub const fn data_port(self) -> u8 {
        match self {
            Self::Sio88 => 0x01,
            Self::TwoSio88 => 0x11,
        }
    }

    /// Status/control address of Port 1 on a fully populated 88-2SIO.
    pub const fn port1_status_port(self) -> Option<u8> {
        match self {
            Self::Sio88 => None,
            Self::TwoSio88 => Some(0x12),
        }
    }

    /// Data address of Port 1 on a fully populated 88-2SIO.
    pub const fn port1_data_port(self) -> Option<u8> {
        match self {
            Self::Sio88 => None,
            Self::TwoSio88 => Some(0x13),
        }
    }
}

impl Default for SerialBoard {
    fn default() -> Self {
        // Preserve the current bundled BASIC 3.2 startup with the front-panel
        // sense switches left at zero.
        Self::Sio88
    }
}

/// Mechanical throughput of the Model 33. The real machine is a 110-baud,
/// 11-unit device producing at most ten characters per second. Faster modes
/// are explicit emulator conveniences rather than claims about real hardware.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Asr33Speed {
    Authentic110,
    Accelerated2x,
    Accelerated4x,
    Instant,
}

impl Asr33Speed {
    pub const ALL: [Self; 4] = [
        Self::Authentic110,
        Self::Accelerated2x,
        Self::Accelerated4x,
        Self::Instant,
    ];

    pub const fn label(self) -> &'static str {
        match self {
            Self::Authentic110 => "110 baud / 10 cps (authentic)",
            Self::Accelerated2x => "20 cps (2x emulation)",
            Self::Accelerated4x => "40 cps (4x emulation)",
            Self::Instant => "Instant (emulation)",
        }
    }

    pub fn char_time(self) -> Duration {
        match self {
            Self::Authentic110 => Duration::from_millis(100),
            Self::Accelerated2x => Duration::from_millis(50),
            Self::Accelerated4x => Duration::from_millis(25),
            Self::Instant => Duration::ZERO,
        }
    }
}

impl Default for Asr33Speed {
    fn default() -> Self {
        Self::Authentic110
    }
}

/// Host text-terminal line rate. Character timing assumes a conventional
/// ten-bit asynchronous frame (start + 8 data + stop), which is also the
/// effective size of common 7-bit ASCII plus parity configurations.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum TerminalSpeed {
    Baud110,
    Baud300,
    Baud1200,
    Baud2400,
    Baud4800,
    Baud9600,
    Baud19200,
    Instant,
}

impl TerminalSpeed {
    pub const ALL: [Self; 8] = [
        Self::Baud110,
        Self::Baud300,
        Self::Baud1200,
        Self::Baud2400,
        Self::Baud4800,
        Self::Baud9600,
        Self::Baud19200,
        Self::Instant,
    ];

    pub const fn label(self) -> &'static str {
        match self {
            Self::Baud110 => "110 baud",
            Self::Baud300 => "300 baud",
            Self::Baud1200 => "1200 baud",
            Self::Baud2400 => "2400 baud",
            Self::Baud4800 => "4800 baud",
            Self::Baud9600 => "9600 baud",
            Self::Baud19200 => "19200 baud",
            Self::Instant => "Instant",
        }
    }

    pub const fn baud(self) -> Option<u32> {
        match self {
            Self::Baud110 => Some(110),
            Self::Baud300 => Some(300),
            Self::Baud1200 => Some(1_200),
            Self::Baud2400 => Some(2_400),
            Self::Baud4800 => Some(4_800),
            Self::Baud9600 => Some(9_600),
            Self::Baud19200 => Some(19_200),
            Self::Instant => None,
        }
    }

    pub fn char_time(self) -> Duration {
        match self.baud() {
            Some(baud) => Duration::from_secs_f64(10.0 / baud as f64),
            None => Duration::ZERO,
        }
    }
}

impl Default for TerminalSpeed {
    fn default() -> Self {
        Self::Baud9600
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Default)]
pub struct MachineConfig {
    pub cpu_model: CpuModel,
    pub ram_size: RamSize,
    pub ram_init: RamInit,
    pub serial_board: SerialBoard,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Default)]
pub struct PeripheralConfig {
    pub asr33_speed: Asr33Speed,
    pub terminal_speed: TerminalSpeed,
}

/// Optional software compatibility workarounds.
///
/// These default to disabled so the emulator reproduces original hardware and
/// software behaviour unless the user explicitly opts into a workaround.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Default)]
pub struct CompatibilityConfig {
    pub basic32_64k_probe_workaround: bool,
}

/// Application convenience behaviour that does not change emulated hardware.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct PreferencesConfig {
    /// Reveal the device physically connected to the bundled BASIC console port
    /// after loading BASIC. This never changes serial cable assignments.
    pub auto_open_basic_console: bool,
}

impl Default for PreferencesConfig {
    fn default() -> Self {
        Self {
            // Preserve the historical RusTair UI behaviour unless the user opts
            // out; the preference only controls window visibility.
            auto_open_basic_console: true,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Default)]
pub struct AppConfig {
    pub machine: MachineConfig,
    pub peripherals: PeripheralConfig,
    pub compatibility: CompatibilityConfig,
    pub preferences: PreferencesConfig,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn classic_altair_cpu_defaults_to_8080_at_two_megahertz() {
        let model = AppConfig::default().machine.cpu_model;
        assert_eq!(model, CpuModel::Intel8080);
        assert_eq!(model.clock_hz(), 2_000_000);
    }

    #[test]
    fn peripheral_timing_defaults_are_historically_sensible() {
        let config = AppConfig::default();
        assert_eq!(config.peripherals.asr33_speed, Asr33Speed::Authentic110);
        assert_eq!(config.peripherals.asr33_speed.char_time(), Duration::from_millis(100));
        assert_eq!(config.peripherals.terminal_speed, TerminalSpeed::Baud9600);
    }

    #[test]
    fn terminal_baud_timing_uses_ten_bit_frames() {
        assert_eq!(
            TerminalSpeed::Baud300.char_time(),
            Duration::from_secs_f64(10.0 / 300.0)
        );
    }

    #[test]
    fn compatibility_workarounds_are_opt_in() {
        let config = AppConfig::default();
        assert!(!config.compatibility.basic32_64k_probe_workaround);
    }

    #[test]
    fn basic_console_auto_open_preserves_previous_default() {
        assert!(AppConfig::default().preferences.auto_open_basic_console);
    }

    #[test]
    fn default_serial_board_is_88_sio() {
        assert_eq!(AppConfig::default().machine.serial_board, SerialBoard::Sio88);
    }

    #[test]
    fn two_sio_exposes_both_standard_port_pairs() {
        let board = SerialBoard::TwoSio88;
        assert_eq!((board.status_port(), board.data_port()), (0x10, 0x11));
        assert_eq!(board.port1_status_port(), Some(0x12));
        assert_eq!(board.port1_data_port(), Some(0x13));
    }
}
