# Increase only the private RusTair FrontPanel command-format buffer on Windows.
#
# Open-SIMH API v12 uses a 1024-byte stack buffer in
# _panel_vsendf_completion().  On Windows it aliases vsnprintf to MSVC's
# _vsnprintf, which returns -1 when the formatted command is truncated rather
# than returning the required length.  RusTair's bulk loader intentionally
# sends multi-DEPOSIT EXECUTE commands larger than 1 KiB (but still below the
# simulator Remote Console's ~4 KiB command buffer), so upstream reports the
# misleading error "Format encoding error while processing '%s'".
#
# The FrontPanel source used here is already a build-tree copy generated by
# rustair-frontpanel.cmake.  Expanding this local formatting buffer does not
# change SCP semantics and never edits the Open-SIMH checkout.

if(CMAKE_VERSION VERSION_LESS 3.19)
    message(FATAL_ERROR "RusTair FrontPanel command-buffer patch requires CMake 3.19 or newer")
endif()

function(rustair_expand_frontpanel_command_buffer)
    set(rustair_source "${CMAKE_BINARY_DIR}/rustair-frontpanel-src/sim_frontpanel.c")
    if(NOT EXISTS "${rustair_source}")
        message(FATAL_ERROR
            "RusTair FrontPanel command-buffer patch ran before the private FrontPanel source existed: ${rustair_source}")
    endif()

    file(READ "${rustair_source}" rustair_contents)
    set(rustair_old "char stackbuf[1024];")
    set(rustair_new "char stackbuf[8192];")

    string(FIND "${rustair_contents}" "${rustair_old}" rustair_first)
    if(rustair_first EQUAL -1)
        message(FATAL_ERROR
            "RusTair could not find Open-SIMH FrontPanel's expected 1024-byte command buffer. Open-SIMH may have changed; review this compatibility patch.")
    endif()

    string(LENGTH "${rustair_old}" rustair_old_len)
    math(EXPR rustair_after_first "${rustair_first} + ${rustair_old_len}")
    string(SUBSTRING "${rustair_contents}" ${rustair_after_first} -1 rustair_tail)
    string(FIND "${rustair_tail}" "${rustair_old}" rustair_second)
    if(NOT rustair_second EQUAL -1)
        message(FATAL_ERROR
            "RusTair found multiple 1024-byte FrontPanel command buffers; refusing an ambiguous patch.")
    endif()

    string(REPLACE "${rustair_old}" "${rustair_new}" rustair_contents "${rustair_contents}")
    file(WRITE "${rustair_source}" "${rustair_contents}")
    message(STATUS
        "RusTair: expanded private FrontPanel formatted-command buffer 1024 -> 8192 bytes for batched loads")
endfunction()

get_property(rustair_frontpanel_buffer_scheduled GLOBAL PROPERTY RUSTAIR_FRONTPANEL_BUFFER_SCHEDULED)
if(NOT rustair_frontpanel_buffer_scheduled)
    set_property(GLOBAL PROPERTY RUSTAIR_FRONTPANEL_BUFFER_SCHEDULED TRUE)
    # rustair-frontpanel.cmake is included first and schedules generation of the
    # private source.  CMake deferred calls execute in scheduling order, so this
    # edit runs immediately after that source/target has been created.
    cmake_language(DEFER DIRECTORY "${CMAKE_SOURCE_DIR}" CALL rustair_expand_frontpanel_command_buffer)
endif()
